apiVersion: batch/v1
kind: Job
metadata:
  name: hgeo-{{ORX_RUN}}
spec:
  activeDeadlineSeconds: 36000
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: reproduction
          image: pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime
          command: ["bash", "-c", "$ORX_SCRIPT"]
          resources:
            requests:
              nvidia.com/gpu: "4"
              cpu: "24"
              memory: "96Gi"
            limits:
              nvidia.com/gpu: "4"
              cpu: "32"
              memory: "128Gi"

